owner: centraldevelopers
repo: status.centralplus.io
sites: # List of endpoints to track
  - name: App Production
    url: https://app.centralplus.io
  - name: App Staging
    url: https://app-staging.centralplus.io
  - name: Admin Production
    url: https://admin.centralplus.io
  - name: Admin Staging
    url: https://admin-staging.centralplus.io
  - name: Api Production
    url: https://api.centralplus.io
    method: GET
  - name: Api Staging
    url: https://api-staging.centralplus.io
    method: GET
status-website:
  cname: status.centralplus.io
  name: Central Status
  logoUrl: https://bank-mobile-files.s3.eu-central-1.amazonaws.com/assets/LogoPlay.png
